#ddev-generated
services:
  pa11y:
    container_name: ddev-${DDEV_SITENAME}-pa11y
    build:
      context: './pa11yBuild'
      args:
        BASE_IMAGE: 'metadrop/docker-pa11y:latest'
        username: $USER
        uid: $DDEV_UID
        gid: $DDEV_GID
    image: dcycle/pa11y:2
    networks: [default, ddev_default]
    restart: "no"
    command: sleep infinity
    entrypoint: ["docker-entrypoint.sh"]
    external_links:
      - web:${DDEV_SITENAME}.${DDEV_TLD}
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ${DDEV_APPROOT}/${PA11Y_CONFIG_PATH:-tests/pa11y/}:/app/config/
      - .:/mnt/ddev_config:ro
      - "ddev-global-cache:/mnt/ddev-global-cache"
