#ddev-generated
services:
  pa11y:
    container_name: ddev-${DDEV_SITENAME}-pa11y
    build:
      context: './pa11yBuild'
      args:
        BASE_IMAGE: ghcr.io/metadrop/aljibe-tools/pa11y:${PA11Y_VERSION:-9.1.1-base1.0.0}
        username: $USER
        uid: $DDEV_UID
        gid: $DDEV_GID
    image: ghcr.io/metadrop/aljibe-tools/pa11y:${PA11Y_VERSION:-9.1.1-base1.0.0}-${DDEV_SITENAME}-built
    user: '$DDEV_UID:$DDEV_GID'
    networks: [default, ddev_default]
    restart: "no"
    init: true
    shm_size: 1gb
    command: sh -c "serve /src/reports -p 9003 --no-clipboard 2>/dev/null & sleep infinity"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
      VIRTUAL_HOST: $DDEV_HOSTNAME
      HTTP_EXPOSE: 9202:9002
      HTTPS_EXPOSE: 9203:9003
    volumes:
      - ${DDEV_APPROOT}/${PA11Y_TESTS_DIR:-tests/pa11y}:/src/tests
      - ${DDEV_APPROOT}/${PA11Y_REPORTS_PATH:-reports/pa11y}:/src/reports
      - .:/mnt/ddev_config:ro
      - "ddev-global-cache:/mnt/ddev-global-cache"
