#!/bin/sh

#ddev-generated

## Description: Run pa11y
## Usage: pa11y [args]
## Example: "ddev pa11y http://metadrop.net --reporter=junit --standard WCAG2A"
## ExecRaw: true
NODE_PATH="/app/node_modules/" /app/node_modules/.bin/pa11y -c /app/config/config.json "$@"


